version: '3.9'

services:
  frontend:
    build: ./
    container_name: project38-test-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    networks:
      - network1
networks:
  network1:
    external: true